### ISSUE TITLE
Rails 5.2 support

### ISSUE THREAD

**Issue by sebasoga** [departurerb/departure#27]
Rails 5.2 [was released today](http://weblog.rubyonrails.org/2018/4/9/Rails-5-2-0-final/) but unfortunately Departure gemspec is locking the gem to only support `5.1.x` versions.

Not sure if it's only about loosening the dependency a bit or changes introduced in Rails 5.2 would break the current implementation of Departure.

**Comment by guilleiguaran** [comment]
This is done in https://github.com/departurerb/departure/pull/28

**Comment by sauloperez** [comment]
Solved by https://github.com/departurerb/departure/pull/28

**Comment by sauloperez** [comment]
Sorry for my late response https://github.com/openfoodfoundation/openfoodnetwork/ is keeping me rather busy. Until https://github.com/departurerb/departure/issues/29 is not done you might be able to move forward using the gem from git. Sorry for any inconvenience, guys.
