### ISSUE TITLE
Release new version for Rails 5.2

### ISSUE THREAD

**Issue by sauloperez** [departurerb/departure#29]
Needed to have https://github.com/departurerb/departure/pull/28 available in Rubygems.

**Comment by guilleiguaran** [comment]
Please merge https://github.com/departurerb/departure/pull/32 before of getting this released 😊

**Comment by sauloperez** [comment]
Yup, I noticed :warning:

**Comment by benlangfeld** [comment]
@sauloperez Do you need some maintenance assistance on this project? @powerhome requires support for Rails 5.2 and would be willing to contribute.

**Comment by sauloperez** [comment]
Indeed! help is needed. Please, join the discussion in https://github.com/departurerb/departure/issues/34

**Comment by madlew** [comment]
Hi, it seem issue #34 got closed, the changes available via master are compliant with Rails 5.2 (on the dependency level, haven't verified yet whether it's working properly or not) - is there any reason why there's no official release?

**Comment by wyhaines** [comment]
On Fri, Apr 17, 2020 at 6:42 AM Lukasz Madlewski <notifications@github.com>
wrote:

> Hi, it seem issue #34 <https://github.com/departurerb/departure/issues/34>
> got closed, the changes available via master are compliant with Rails 5.2
> (on the dependency level, haven't verified yet whether it's working
> properly or not) - is there any reason why there's no official release?
>
Unless there is an objection from other quarters, I can see about doing one
this weekend.


Thank you,

Kirk Haines

**Comment by vivekbisen** [comment]
Is there any updates on this?

**Comment by wyhaines** [comment]
On Fri, Jun 5, 2020 at 8:15 AM Vivek Bisen <notifications@github.com> wrote:

> Is there any updates on this?
>
I merged the Rails 6 PR.

I'll do some sanity checking QA on everything and finally get the new
release done.


Kirk Haines

**Comment by cleicar** [comment]
Hi @wyhaines Thanks so much for maintain departure! We are using in in many of our projects at [Power](https://github.com/powerhome/).

Now that the PR is [merged](https://github.com/departurerb/departure/pull/46), when do you plan to release the new version?

We would be happy to assist with any help you need.

**Comment by cleicar** [comment]
The version was released! https://rubygems.org/gems/departure/versions/6.2.0
