### ISSUE TITLE
Sharing the workload

### ISSUE THREAD

**Issue by sauloperez** [departurerb/departure#34]
Hi everyone, 

this is a call for those regular contributors to jump on and share the workload of maintaining Departure.

My situation has changed a lot since the project started. I spend most of my time shaping [Coopdevs](github.com/coopdevs/) and pushing forward [Open Food Network](https://github.com/openfoodfoundation/openfoodnetwork) which leaves me little room for anything else. Besides, I no longer use it on my projects so I don't have direct incentive to maintain it although I consider it a very useful tool.

Which one of you @guilleiguaran, @wyhaines, @garettarrowood, @aserafin, @muffinista would be open for that? thoughts?

**Comment by sauloperez** [comment]
That's great @wyhaines! Can start opening PRs for those issues? Then I can work on giving you permissions and release the necessary versions.

**Comment by muffinista** [comment]
Sorry, I've been offline for a few days. I'm happy to help too. I'm not using the gem at work but we do use pt-osc all the time, and I expect to start using departure again once we're done with a Rails 5 upgrade.

**Comment by sauloperez** [comment]
great news @muffinista !

**Comment by wyhaines** [comment]
I have gone through our private repo, and all of the changes there have already been merged. I have a change that I need to finish and get ready to merge, but I can always just switch it to the main gem's line and do it directly, now.  Let me know what info you need, @sauloperez .

**Comment by guilleiguaran** [comment]
@sauloperez as @wyhaines mentioned I'm happy to help!!

**Comment by sauloperez** [comment]
> but I can always just switch it to the main gem's line and do it directly, now

Yes, just open a PR so that we can review it.

**Comment by wyhaines** [comment]
On Fri, Jun 15, 2018 at 5:53 PM Pau Pérez Fabregat <notifications@github.com>
wrote:

> but I can always just switch it to the main gem's line and do it directly,
> now
>
> Yes, just open a PR so that we can review it.
>

We actually have this one:

https://github.com/departurerb/departure/pull/33

Still pending.

If you want to give me (and Guillermo Iguaran) access to merge and do
releases, we can take care of getting a new release out.


Thanks,

Kirk Haines

**Comment by sauloperez** [comment]
I just sent you guys an invite to join the core maintainers team and gave you write access. Let me know if that's enough.

I would also like to find some time to have a call to meet and share our ideas to move Departure forward.

**Comment by sauloperez** [comment]
When does a videocall fit for you?

**Comment by wyhaines** [comment]
On Thu, Jul 12, 2018 at 11:49 PM Pau Pérez Fabregat <
notifications@github.com> wrote:

> When does a videocall fit for you?
>
 What timezone are you in? I can be fairly flexible.


Kirk Haines

>

**Comment by sauloperez** [comment]
I'm based in Barcelona, so UTC+02:00. I have a flexible schedule so let's set a date. What's your time zone?

**Comment by wyhaines** [comment]
On Mon, Jul 16, 2018 at 5:55 PM Pau Pérez Fabregat <notifications@github.com>
wrote:

> I'm based in Barcelona, so UTC+02:00. I have a flexible schedule so let's
> set a date. What's your time zone?
>
I live in the US, Wyoming, so I'm in MDT (UTC-06:00), but I can accommodate
whatever works for you.


Kirk Haines

**Comment by sauloperez** [comment]
Great! we just had the call and we decided the following:

* We'll have adhoc backports. Just when they are requested.
* It's up to the core maintainers to prepare releases.
* The focus is releasing a version with Rails 5.2 support.
* I'll still code review and document if it's needed. I'll also keep being admin of the repo.

Thanks @wyhaines and @benlangfeld for your time.
