### ISSUE TITLE
Support for Rails 6.1

### ISSUE THREAD

**Issue by vivekbisen** [departurerb/departure#57]
Now that Rails 6.1 is out, has there been any attempt to upgrade the gem for new version of AR? The dependency limits it to < 6.1.

**Comment by wyhaines** [comment]
Not that I am aware of yet.  It needs to be tested against 6.1 to see if anything breaks.

**Comment by sharang-d** [comment]
Can you release a new gem version, please?
We're referencing the commit SHA for now and all works well!

**Comment by wyhaines** [comment]
You are running against Rails 6.1?

I don't currently have a 6.1 project to test against.

**Comment by sharang-d** [comment]
Yes, been running against https://github.com/departurerb/departure/commit/c5f531d7c142423980faa4101bc6a78a0489c738 for a while now.

**Comment by indiebrain** [comment]
What are the outstanding impediments to cutting a proper release of the `departure` gem which includes support for Rails 6.1? Anything the community can help with?

**Comment by wyhaines** [comment]
Me getting my ducks in a row, honestly. I'm working on prepping a release right now.

**Comment by wyhaines** [comment]
https://github.com/departurerb/departure/releases/tag/v6.3.0

```
❯ gem search departure

*** REMOTE GEMS ***

departure (6.3.0)
```

**Comment by indiebrain** [comment]
The "ducks in a row" impediment is one with which I can relate. Many thanks for such a swift reply. I appreciate the work, friend.
