### ISSUE TITLE
Cannot update to Rails 6.1.4

### ISSUE THREAD

**Issue by dsalzr** [departurerb/departure#68]
Looks like departure is capped at rails <= 6.1

```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    departure (~> 6.3.0) was resolved to 6.3.0, which depends on
      activerecord (>= 5.2.0, <= 6.1)

    rails (>= 6.1.4, < 6.2) was resolved to 6.1.4, which depends on
      activerecord (= 6.1.4)
```

Can you please cut a new release to allow updates?

**Comment by voraciousdev** [comment]
I'm also running into this issue.

**Comment by voraciousdev** [comment]
I see the fix is already in main. Is there an ETA for the next release?

**Comment by bsimpson** [comment]
@dsalzr Would this look like `< 6.2` so we can get any future path releases of Rails as well?

**Comment by dsalzr** [comment]
@bsimpson Thats sounds correct 👍🏼

**Comment by ryanmrodriguez** [comment]
Is there anything blocking a new release that the community can help with?

**Comment by bmt-tock** [comment]
Any update on this? It would be great to have a release with this change in it.

**Comment by benlangfeld** [comment]
@takanabe or @sikachu Any chance of some attention on this one? I see you both [got added as maintainers recently](https://github.com/departurerb/departure/issues/70).

**Comment by xjunior** [comment]
Hello. We use this tool in our organization and we would gladly help maintain it. Can you add me as a maintainer?

**Comment by sikachu** [comment]
I actually don't have push permission for this gem, so that's why I didn't push it ...

@wyhaines would you be able to handle a release? Otherwise, would you mind adding me on RubyGems?

**Comment by benlangfeld** [comment]
@wyhaines We'd really appreciate some help here.

**Comment by voraciousdev** [comment]
While it's not a permanent solution, others that land here can use the following configuration in the `Gemfile` to get the latest changes while we wait on a release.

```ruby
# Gemfile
gem "departure", github: "departurerb/departure", branch: "master"
```

**Comment by benlangfeld** [comment]
Released in https://github.com/departurerb/departure/pull/82
