### ISSUE TITLE
Can we add some developers as the maintainer of this gem?

### ISSUE THREAD

**Issue by takanabe** [departurerb/departure#70]
Hi @wyhaines! 

Would you mind if we can add some Cookpad developers to the maitener of this gem? Since we've started developing this gem when we are in Cookpad and the team still uses the gem in production.

So, Cookpad developers also can push PRs and reviews issues/PRs so we can improve the support of newer version of Rails. What do you think?

Note:

In fact, I don't understand who has admin permissions of the depaturerb organization because I could not find any people in the organization. Do you know who owns the organization?

**Comment by wyhaines** [comment]
Mostly, I do. Everyone else is pretty inactive, and I get so busy sometimes that I miss the discussions, and then have to catch up later.  :)

Who do you suggest adding?

**Comment by takanabe** [comment]
@sikachu & @takanabe ATM 📝

**Comment by chrismaximin** [comment]
_(Hopefully I'm not breaking any etiquette by mentioning this:)_

You may be interested in using https://github.com/gumroad/alterity instead, which I wrote for @gumroad as an alternative Departure. It doesn't rely on Rails internal/private methods, so it's pretty stable.
It also has a few added functionalities, including: automatic handling of replicas, hooks pre/during/post migration.

**Comment by sauloperez** [comment]
oh nice @chrismaximin ! Good to see other approaches!

@takanabe I already added you and @sikachu as maintainers. Let us know if you are still interested though.

**Comment by takanabe** [comment]
Thanks!

**Comment by benlangfeld** [comment]
@sauloperez @wyhaines Can you please add myself (ben@langfeld.me) and @xjunior (chjunior@gmail.com), including ability to push gem releases? There are several issues here which are stalled.
