### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by sauloperez** [departurerb/departure#9]
Support for Rails v5.1 is currently being implemented in https://github.com/redbooth/departure/pull/81. Although there should be very little difference between the changes required for 5.1 and what is needed for 5.0, it is still to be done.

https://github.com/redbooth/departure/issues/41 is the original issue which contains the body of the discussion.

**Comment by etagwerker** [comment]
@sauloperez I just submitted PR #12 to solve this issue. It's still WIP.

**Comment by sauloperez** [comment]
Solved in #13

**Comment by sauloperez** [comment]
Release with Rails 5.0 support published! :tada: https://rubygems.org/gems/departure/versions/5.0.0

**Comment by wyhaines** [comment]
Will there be a separate branch pegged to 5.1? I was under the assumption that the 5.0 release would work on both 5.0 and 5.1, with @etagwerker's contributions, but it is locked to ~> 5.0.0.

**Comment by sauloperez** [comment]
Yes, my intention is to have a separate branch for it, as happens with Rails.
